#ifndef INCLUDE_VPSDEMO_TRANSPORT_REGISTRY_PROTOCOL_H_
#define INCLUDE_VPSDEMO_TRANSPORT_REGISTRY_PROTOCOL_H_

#include <registry_protocol.h>

#endif  // INCLUDE_VPSDEMO_TRANSPORT_REGISTRY_PROTOCOL_H_
