#ifndef INCLUDE_VPSDEMO_TRANSPORT_VES_BOOTSTRAP_STUB_H_
#define INCLUDE_VPSDEMO_TRANSPORT_VES_BOOTSTRAP_STUB_H_

#include <ves_bootstrap_stub.h>

#endif  // INCLUDE_VPSDEMO_TRANSPORT_VES_BOOTSTRAP_STUB_H_
