#ifndef INCLUDE_VPSDEMO_TESTKIT_TESTKIT_ASYNC_CLIENT_H_
#define INCLUDE_VPSDEMO_TESTKIT_TESTKIT_ASYNC_CLIENT_H_

#include <testkit_async_client.h>

#endif  // INCLUDE_VPSDEMO_TESTKIT_TESTKIT_ASYNC_CLIENT_H_
